name: aidx
description: A medical assistant app with wearable integration.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  cloud_firestore: ^5.6.11
  flutter_blue_plus: ^1.15.8
  geolocator: ^13.0.4
  http: ^1.1.0
  intl: ^0.18.0
  flutter_feather_icons: ^2.0.0+1
  url_launcher: ^6.2.5
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.4.1
  timezone: ^0.9.4
  flutter_local_notifications: ^17.1.2
  firebase_messaging: ^15.1.5
  share_plus: ^11.0.0
  timeline_tile: ^2.0.0
  image_picker: ^1.0.7
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  firebase_storage: ^12.4.9
  firebase_core_web: ^2.24.0
  firebase_auth_web: ^5.8.13
  firebase_storage_web: ^3.6.22
  permission_handler: ^11.4.0
  permission_handler_android: ^12.1.0
  characters: ^1.3.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  google_sign_in: 6.1.5
  auto_size_text: ^3.0.0
  speech_to_text: ^7.1.0
  flutter_tts: ^3.8.5
  connectivity_plus: ^5.0.2
  android_intent_plus: ^5.3.0
  just_audio: ^0.9.37
  syncfusion_flutter_charts: ^29.1.38
  qr_flutter: ^4.1.0
  path_provider: ^2.1.2
  sensors_plus: ^4.0.2
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  camera: ^0.11.0+1
  device_info_plus: ^10.1.0
  mobile_scanner: ^6.0.11
  flutter_sound: ^9.2.13
  audio_session: ^0.1.16
  google_generative_ai: ^0.2.2
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # ✅ Add these:
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/

# ✅ Add this at the END of the file (same indentation level as flutter:)
flutter_native_splash:
  color: "#D8E7EF"
  image: assets/images/logoFirst.png
  android_12:
    color: "#D8E7EF"
    image: assets/images/logo123.png


flutter_icons:
  android: true
  ios: true
  image_path: assets/images/logo2.png
